services:
  nginx:
    image: nginx:latest

    depends_on:
      - backend

    volumes:
      - ./:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - ${PORT}:80

  postgres:
    image: postgres:17-alpine
    env_file: .env

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/

    depends_on:
      - postgres

    volumes:
      - ./:/app

    user: ${DOCKER_USER}
    working_dir: /app/backend
    env_file: .env
    command: /app/backend/docker-entrypoint.sh

  frontend:
    build:
      context: ./frontend/

    volumes:
      - ./:/app

    user: ${DOCKER_USER}
    working_dir: /app/frontend
    env_file: .env
    command: /app/frontend/docker-entrypoint.sh
