# Generated by Django 4.2.20 on 2025-08-10 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pillowfort.models.asset
import pillowfort.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=256, validators=[pillowfort.validators.validate_name], verbose_name='Name')),
                ('file', models.FileField(upload_to=pillowfort.models.asset.upload_to, validators=[pillowfort.validators.validate_png])),
                ('generated', models.BooleanField(default=False, verbose_name='Generated')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('name', models.CharField(blank=True, max_length=256, null=True, validators=[pillowfort.validators.validate_name], verbose_name='Name')),
                ('verbose_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Verbose Name')),
                ('url', models.TextField(blank=True, editable=False, null=True, verbose_name='URL')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('map_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Map Data')),
                ('optimized_map_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Optimized Map Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pillowfort.space', verbose_name='Parent Space')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
            },
        ),
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('name', models.CharField(max_length=256, validators=[pillowfort.validators.validate_name], verbose_name='Name')),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to='pillowfort.asset', verbose_name='Asset')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets', to='pillowfort.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Tileset',
                'verbose_name_plural': 'Tilesets',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pillowfort.space', verbose_name='Space'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('character_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Character Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('home_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pillowfort.space', verbose_name='Home Space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('can_edit', models.BooleanField(default=False, verbose_name='can edit')),
                ('can_grant_access', models.BooleanField(default=False, verbose_name='can grant access')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillowfort.account', verbose_name='Account')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='pillowfort.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Access Rule',
                'verbose_name_plural': 'Access Rules',
            },
        ),
    ]
