# Generated by Django 4.2.20 on 2025-08-10 15:39

from django.db import migrations, models
import django.db.models.deletion
import pillowfort.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pillowfort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('type', models.CharField(choices=[('map', 'Map'), ('character', 'Character'), ('entity', 'Entity')], max_length=10)),
                ('name', models.CharField(max_length=256, validators=[pillowfort.validators.validate_name], verbose_name='Name')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Data')),
                ('optimized_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Optimized Data')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='Config')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='pillowfort.space', verbose_name='Space')),
            ],
            options={
                'verbose_name': 'Blueprint',
                'verbose_name_plural': 'Blueprints',
            },
        ),
    ]
